[workspace]
authors = ["Ben Woodcroft <benjwoodcroft@gmail.com>"]
channels = ["conda-forge","bioconda"]
name = "singlem-sra-processing"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[feature.main.dependencies]
python = ">=3.10"
snakemake = "*"
snakemake-executor-plugin-cluster-generic = "*"
conda = ">=24.7.1"
polars = "*"
extern = "*"
jupyterlab = "*"
nbconvert = "*"
r = "*"
r-irkernel = "*"
"r-data.table" = "*"
r-ggplot2 = "*"
r-ggbeeswarm = "*"
ncbi-datasets-cli = "*"
bird_tool_utils_python = "*"
tqdm = "*"
scipy = "*"

[feature.singlem.dependencies]
singlem = "=0.18.3" # no particular reason for this version, just the latest at the time of writing
iso8601 = "*"

[feature.kingfisher.dependencies]
kingfisher = ">=0.4.1"

[environments]
default = ["main"]
main = ["main"]
singlem = ["singlem"]
kingfisher = ["kingfisher"]
